management:
   health:
      circuitbreakers:
         enabled: true
   endpoints:
      web:
         exposure:
            include: "*"
      endpoint:
         health:
            show-details: "ALWAYS"

resilience4j:
   circuitbreaker:
      instances:
         paymentService:
            registerHealthIndicator: true
            allowHealthIndicatorToFail: false
            eventConsumerBufferSize: 10
            failureRateThreshold: 50
            minimumNumberOfCalls: 4
            automaticTransitionFromOpenToHalfOpenEnabled: true
            waitDurationInOpenState: 5s
            permittedNumberOfCallsInHalfOpenState: 2
            slidingWindowSize: 10
            slidingWindowType: COUNT_BASED

retry:
      instances:
         paymentService:
            maxRetryAttempts: 5
            waitDuration: 10s